// <auto-generated />
using System;
using FindJob.Models.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FindJob.Migrations
{
    [DbContext(typeof(FjDbContext))]
    [Migration("20220903183921_Profiles")]
    partial class Profiles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("FindJob.Models.ViewModels.EmployerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("bytea");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmployerProfil");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.FjImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.FjResponses", b =>
                {
                    b.Property<Guid>("ResumeGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VacancyGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("FjResponsesTypes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.HasKey("ResumeGuid", "VacancyGuid");

                    b.HasIndex("VacancyGuid");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Expirience")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("Post")
                        .HasColumnType("text");

                    b.Property<double?>("Salary")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WorkerProfilId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("WorkerProfilId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployerProfilId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Expirience")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("Post")
                        .HasColumnType("text");

                    b.Property<double?>("Salary")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EmployerProfilId");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.WorkerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("DefaultPicture")
                        .HasColumnType("bytea");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkerProfil");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.FjResponses", b =>
                {
                    b.HasOne("FindJob.Models.ViewModels.Resume", "Resume")
                        .WithMany("Responses")
                        .HasForeignKey("ResumeGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindJob.Models.ViewModels.Vacancy", "Vacancy")
                        .WithMany("Responses")
                        .HasForeignKey("VacancyGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.Resume", b =>
                {
                    b.HasOne("FindJob.Models.ViewModels.FjImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("FindJob.Models.ViewModels.WorkerProfile", "WorkerProfil")
                        .WithMany("Resumes")
                        .HasForeignKey("WorkerProfilId");

                    b.Navigation("Image");

                    b.Navigation("WorkerProfil");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.Vacancy", b =>
                {
                    b.HasOne("FindJob.Models.ViewModels.EmployerProfile", "EmployerProfil")
                        .WithMany("Vacancies")
                        .HasForeignKey("EmployerProfilId");

                    b.Navigation("EmployerProfil");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.EmployerProfile", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.Resume", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.Vacancy", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("FindJob.Models.ViewModels.WorkerProfile", b =>
                {
                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
